spring.application.name=RedesJava
spring.jpa.show-sql=true
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=system
spring.datasource.password=senhadificil
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
server.port=8080